name: BuildMode
author: UltraDev
main: xyz.ultradev.buildmode.BuildMode
version: 1.0.0
softdepend:
  - WorldGuard
commands:
  buildmode:
    aliases: [build]
    description: "The main command for the BuildMode plugin"